//! SAR template engine — renders aggregated activity into NFIU/CBN regulatory format.
//!
//! NFIU (Nigerian Financial Intelligence Unit) accepts JSON-structured STR/SAR reports.
//! CBN (Central Bank of Nigeria) accepts XML.  We produce both; the filing service
//! picks the right one based on `RegulatoryAuthority`.

use chrono::Utc;

use super::models::{ActivitySnapshot, RegulatoryAuthority, SarReport};

/// Render a SAR report payload for the given authority.
pub fn render(report: &SarReport, snapshot: &ActivitySnapshot, authority: &RegulatoryAuthority) -> String {
    match authority {
        RegulatoryAuthority::Nfiu => render_nfiu_json(report, snapshot),
        RegulatoryAuthority::Cbn => render_cbn_xml(report, snapshot),
    }
}

fn render_nfiu_json(report: &SarReport, snapshot: &ActivitySnapshot) -> String {
    let payload = serde_json::json!({
        "report_type": "SAR",
        "report_id": report.id,
        "filing_institution": "Aframp",
        "filing_date": Utc::now().format("%Y-%m-%d").to_string(),
        "subject": {
            "wallet_address": report.wallet_address,
            "linked_bank_accounts": snapshot.linked_bank_accounts,
            "ip_addresses": snapshot.ip_addresses,
        },
        "suspicious_activity": {
            "transaction_id": report.transaction_id,
            "observation_window_hours": snapshot.window_hours,
            "transaction_count": snapshot.transaction_count,
            "total_volume": snapshot.total_volume,
            "transactions": snapshot.recent_transactions,
        },
        "narrative": format!(
            "Automated SAR generated by Aframp AML engine. {} transactions totalling {} \
             detected within {} hours for wallet {}.",
            snapshot.transaction_count,
            snapshot.total_volume,
            snapshot.window_hours,
            report.wallet_address,
        ),
        "aml_case_id": report.aml_case_id,
    });
    serde_json::to_string_pretty(&payload).unwrap_or_default()
}

fn render_cbn_xml(report: &SarReport, snapshot: &ActivitySnapshot) -> String {
    let txns: String = snapshot
        .recent_transactions
        .iter()
        .map(|t| {
            format!(
                r#"    <Transaction id="{}" type="{}" amount="{}" currency="{}" status="{}" date="{}"/>"#,
                t.transaction_id,
                t.tx_type,
                t.amount,
                t.currency,
                t.status,
                t.created_at.format("%Y-%m-%dT%H:%M:%SZ"),
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<SuspiciousActivityReport xmlns="urn:cbn:sar:v1">
  <ReportId>{}</ReportId>
  <FilingInstitution>Aframp</FilingInstitution>
  <FilingDate>{}</FilingDate>
  <AmlCaseId>{}</AmlCaseId>
  <Subject>
    <WalletAddress>{}</WalletAddress>
    <LinkedBankAccounts>{}</LinkedBankAccounts>
    <IpAddresses>{}</IpAddresses>
  </Subject>
  <SuspiciousActivity>
    <TransactionId>{}</TransactionId>
    <ObservationWindowHours>{}</ObservationWindowHours>
    <TransactionCount>{}</TransactionCount>
    <TotalVolume>{}</TotalVolume>
    <Transactions>
{}
    </Transactions>
  </SuspiciousActivity>
</SuspiciousActivityReport>"#,
        report.id,
        Utc::now().format("%Y-%m-%d"),
        report.aml_case_id,
        report.wallet_address,
        snapshot.linked_bank_accounts.join(", "),
        snapshot.ip_addresses.join(", "),
        report.transaction_id,
        snapshot.window_hours,
        snapshot.transaction_count,
        snapshot.total_volume,
        txns,
    )
}
